export const BOOKS = [
    {
        id: 0,
        title: "The Rook",
        author: "M.D. Gardner",
        category: "Adventure",
        image: "https://images.unsplash.com/photo-1550368566-f9cc32d7392d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80",
        featured: true,
        description: "When all else falls in the war on magic, he alone stands tall, thanks to his wits and rings.",
        length: 242,
        release: "10/23/19",
        language: "English",
        rating: 4,
        ratingCount: 313,
    },
    {
        id: 1,
        title: "Black Horizons",
        author: "James Lloyd",
        category: "Adventure",
        image: "https://images.unsplash.com/photo-1472145246862-b24cf25c4a36?ixlib=rb-1.2.1&auto=format&fit=crop&w=1502&q=80",
        featured: false,
        description: "A WW2 pilot flies through a storm cloud and a find a different wold on the other side.",
        length: 213,
        release: "09/29/20",
        language: "English",
        rating: 5,
        ratingCount: 34,
    },
    {
        id: 2,
        title: "Brawler",
        author: "Bo Boxman",
        category: "Adventure",
        image: "https://images.unsplash.com/photo-1552072092-7f9b8d63efcb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
        featured: false,
        description: "Cain has been able to punch his way through most his troubles, but the real fight starts now!",
        length: 200,
        release: "01/02/16",
        language: "English",
        rating: 3,
        ratingCount: 777,
    },
    {
        id: 3,
        title: "The Guide to Graphite",
        author: "Jenson Julius",
        category: "Art",
        image: "https://images.unsplash.com/photo-1593435221502-c5d7bfc26cab?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1000&q=80",
        featured: false,
        description: "Almost any form of art starts with a sketch, but sketching is an art form in itself too.",
        length: 109,
        release: "03/06/09",
        language: "English",
        rating: 4,
        ratingCount: 1292,
    },
    {
        id: 4,
        title: "Painting 101",
        author: "Dottie Numan",
        category: "Art",
        image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1502&q=80",
        featured: false,
        description: "Covering the basics of painting strokes, color blending, and artistic styles.",
        length: 93,
        release: "06/02/2014",
        language: "English",
        rating: 2,
        ratingCount: 413,
    },
    {
        id: 5,
        title: "Painting 102",
        author: "Dottie Numan",
        category: "Art",
        image: "https://images.unsplash.com/photo-1596567181723-ba7d15eacefb?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=564&q=80",
        featured: false,
        description: "Following up the basics with the differences amongst painting tools and canvases.",
        length: 103,
        release: "08/13/2015",
        language: "English",
        rating: 4,
        ratingCount: 255,
    },
    {
        id: 6,
        title: "The Art of Atomic Bombs",
        author: "Bale Gordon",
        category: "Biography",
        image: "https://images.unsplash.com/photo-1503216963294-431766a5a929?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1500&q=80",
        featured: false,
        description: "Einstein has been called a mad scientist and a genius, but one thing he was was conflicted.",
        length: 349,
        release: "07/21/14",
        language: "English",
        rating: 5,
        ratingCount: 789,
    },
    {
        id: 7,
        title: "Of Balconies and Bullets",
        author: "Dr. Gertrude James",
        category: "Biography",
        image: "https://images.unsplash.com/photo-1562329265-95a6d7a83440?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1328&q=80",
        featured: false,
        description: "President Lincoln is one of the most famous presidents, but what is the story of his killer?",
        length: 250,
        release: "12/10/17",
        language: "English",
        rating: 4,
        ratingCount: 82,
    },
    {
        id: 8,
        title: "Oh Mother!",
        author: "Johnny Lou Mona",
        category: "Biography",
        image: "https://images.unsplash.com/photo-1544652406-55174175da25?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=668&q=80",
        featured: false,
        description: "Behind every man is a mother, but what of Mr. Freud, and his relationship with his parent.",
        length: 163,
        release: "05/30/10",
        language: "English",
        rating: 3,
        ratingCount: 469,
    },
    {
        id: 9,
        title: "By The Numbers",
        author: "Luke Limon",
        category: "Business",
        image: "https://images.unsplash.com/photo-1506555191898-a76bacf004ca?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=668&q=80",
        featured: true,
        description: "An MBA is just a degree. If you want to get a business education, start here!",
        length: 161,
        release: "04/07/10",
        language: "English",
        rating: 5,
        ratingCount: 1000,
    },
    {
        id: 10,
        title: "Theory of Nothing",
        author: "Lana Lordes",
        category: "Business",
        image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1500&q=80",
        featured: false,
        description: "Efficiency at work starts with a clear mind and clean schedule, and the theory of nothing.",
        length: 231,
        release: "12/12/19",
        language: "English",
        rating: 4,
        ratingCount: 71,
    },
    {
        id: 11,
        title: "Lord of Handshakes",
        author: "Jamima Louise",
        category: "Business",
        image: "https://images.unsplash.com/photo-1496115965489-21be7e6e59a0?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=668&q=80",
        featured: false,
        description: "Bargains, agreements, and compromise are the core of any business, so master them.",
        length: 154,
        release: "01/19/18",
        language: "English",
        rating: 2,
        ratingCount: 17,
    },
    {
        id: 12,
        title: "Pretty Pretty Platypus",
        author: "B.N. Barnes",
        category: "Children's",
        image: "https://images.unsplash.com/photo-1605687720340-696371e40e38?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1500&q=80",
        featured: false,
        description: "While Platipi are very strange, they are beautiful in their own way!",
        length: 44,
        release: "08/09/18",
        language: "English",
        rating: 5,
        ratingCount: 111,
    },
    {
        id: 13,
        title: "The Penguin Sweater",
        author: "Watson Wayans",
        category: "Children's",
        image: "https://images.unsplash.com/photo-1517783999520-f068d7431a60?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1500&q=80",
        featured: false,
        description: "There once was a penguin who went on an adventure with his favorite sweater in hand.",
        length: 23,
        release: "10/01/11",
        language: "English",
        rating: 3,
        ratingCount: 992,
    },
    {
        id: 14,
        title: "Puddle Power",
        author: "Bonnie Clyde",
        category: "Children's",
        image: "https://images.unsplash.com/photo-1540479859555-17af45c78602?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1500&q=80",
        featured: false,
        description: "Every kid has a superhero inside. All they need is a pair of rainboots and a puddle!",
        length: 33,
        release: "12/13/17",
        language: "English",
        rating: 5,
        ratingCount: 357,
    },
    {
        id: 15,
        title: "The Jogger's Bible",
        author: "Lou Folds",
        category: "Education",
        image: "https://images.unsplash.com/photo-1496163668521-39614a16b23f?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1778&q=80",
        featured: false,
        description: "Jogging is the perfect middle ground for fat burn and cardio and it's not as easy as you'd think.",
        length: 170,
        release: "06/12/18",
        language: "English",
        rating: 4,
        ratingCount: 200,
    },
    {
        id: 16,
        title: "Development for Geniuses",
        author: "Dr. F. Ferris",
        category: "Education",
        image: "https://images.unsplash.com/photo-1518773553398-650c184e0bb3?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1500&q=80",
        featured: false,
        description: "There are a lot of books for dummies out there, but this is how you make a developer better!",
        length: 492,
        release: "05/19/15",
        language: "English",
        rating: 3,
        ratingCount: 82,
    },
    {
        id: 17,
        title: "Alphabets of the World",
        author: "James Beards",
        category: "Education",
        image: "https://images.unsplash.com/photo-1580753318747-49bc43e942e5?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=668&q=80",
        featured: false,
        description: "Everyone learns the alphabet as a kid, but which one? Just how many alphabets are there?",
        length: 275,
        release: "11/22/03",
        language: "English",
        rating: 4,
        ratingCount: 2345,
    },
    {
        id: 18,
        title: "The Big One",
        author: "Mallory Dunkine",
        category: "History",
        image: "https://images.unsplash.com/photo-1482348838597-b97cc6c86a88?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1502&q=80",
        featured: false,
        description: "California has never been shaken more than in 1989, when the state's largest earthquake broke San Francisco.",
        length: 168,
        release: "10/10/20",
        language: "English",
        rating: 5,
        ratingCount: 9,
    },
    {
        id: 19,
        title: "Broken Arrows",
        author: "Steve Nash",
        category: "History",
        image: "https://images.unsplash.com/photo-1597824583262-90e3153a21eb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80",
        featured: false,
        description: "One of the most defining historical moments, and saddest, in US history is the Trail of Tears. It shouldn't be forgotten.",
        length: 333,
        release: "3/30/18",
        language: "English",
        rating: 4,
        ratingCount: 543,
    },
    {
        id: 20,
        title: "Breaking America",
        author: "Dr. Vardy Stone",
        category: "History",
        image: "https://images.unsplash.com/photo-1601319759324-f311bd99ebb9?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=668&q=80",
        featured: false,
        description: "It's no surprise that a pandemic can bring America to it's knees, but poor leadership shouldn't.",
        length: 317,
        release: "11/22/20",
        language: "English",
        rating: 5,
        ratingCount: 5,
    },
    {
        id: 21,
        title: "The Calm",
        author: "Madra Menzo",
        category: "Home",
        image: "https://images.unsplash.com/photo-1480074568708-e7b720bb3f09?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=2553&q=80",
        featured: false,
        description: "Life is a storm, but your home can be the calm. Learn to make your home your getaway.",
        length: 333,
        release: "03/30/18",
        language: "English",
        rating: 4,
        ratingCount: 435,
    },
    {
        id: 22,
        title: "Clean House, Happy Life",
        author: "Joseph Goodfellow",
        category: "Home",
        image: "https://images.unsplash.com/photo-1528740561666-dc2479dc08ab?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=668&q=80",
        featured: false,
        description: "The phrase Happy Wife Happy Life has been around for ages, but it's all wrong!",
        length: 260,
        release: "01/06/05",
        language: "English",
        rating: 5,
        ratingCount: 2109,
    },
    {
        id: 23,
        title: "Green Thumbs",
        author: "Shelby Moss",
        category: "Home",
        image: "https://images.unsplash.com/photo-1459156212016-c812468e2115?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=698&q=80",
        featured: false,
        description: "You don't need a garden or a botany degree to give your home a touch of plant life!",
        length: 129,
        release: "02/04/20",
        language: "English",
        rating: 3,
        ratingCount: 15,
    },
    {
        id: 24,
        title: "Fiona Found",
        author: "Molli Miles",
        category: "Mystery",
        image: "https://images.unsplash.com/photo-1528728329032-2972f65dfb3f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80",
        featured: true,
        description: "One day she's falls asleep in her family's field in 1297. She wakes up in Berlin 2020.",
        length: 333,
        release: "02/14/19",
        language: "English",
        rating: 5,
        ratingCount: 543,
    },
    {
        id: 25,
        title: "What the Hell?",
        author: "BB Kaye",
        category: "Mystery",
        image: "https://images.unsplash.com/photo-1541051595295-e7d4ae8b845f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80",
        featured: false,
        description: "Nick thought things was good until he died and went to Hell. Can it get any worse? Oh yes!",
        length: 168,
        release: "06/11/20",
        language: "English",
        rating: 2,
        ratingCount: 49,
    },
    {
        id: 26,
        title: "Slippery Slope",
        author: "Wanda Bones",
        category: "Mystery",
        image: "https://images.unsplash.com/photo-1600454252672-d87dc589afdf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=666&q=80",
        featured: false,
        description: "What started out as a hankering for good cookies led to life as a millionare crime boss.",
        length: 375,
        release: "02/02/20",
        language: "English",
        rating: 4,
        ratingCount: 246,
    },
    {
        id: 27,
        title: "The Dawn",
        author: "Kaya Dee Knox",
        category: "Romance",
        image: "https://images.unsplash.com/photo-1473679408190-0693dd22fe6a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
        featured: true,
        description: "A once-in-a-lifetime sunrise accidentally brings two old friends back together.",
        length: 140,
        release: "06/20/18",
        language: "English",
        rating: 5,
        ratingCount: 113,
    },
    {
        id: 28,
        title: "Translating Love",
        author: "Nick Sparkles",
        category: "Romance",
        image: "https://images.unsplash.com/photo-1486819118102-d9171cf69a92?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1049&q=80",
        featured: false,
        description: "During her gap year, Marta falls in love with an incredible girl, but she can't understand her.",
        length: 168,
        release: "10/10/20",
        language: "English",
        rating: 5,
        ratingCount: 9,
    },
    {
        id: 29,
        title: "Rose-Colored Ink",
        author: "Becky Boop",
        category: "Romance",
        image: "https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=639&q=80",
        featured: false,
        description: "A love poem written by a young girl to her elementary crush resurfaces after 22 years",
        length: 191,
        release: "02/14/18",
        language: "English",
        rating: 3,
        ratingCount: 115,
    },
    {
        id: 30,
        title: "Electrifying",
        author: "Dr. Ma Farrow",
        category: "Science",
        image: "https://images.unsplash.com/photo-1516912481808-3406841bd33c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1283&q=80",
        featured: false,
        description: "What is electricity, and just how did we get from lightning to light bulb?",
        length: 254,
        release: "11/22/19",
        language: "English",
        rating: 4,
        ratingCount: 231,
    },
    {
        id: 31,
        title: "Mask or No Mask?",
        author: "Scott Bonnet",
        category: "Science",
        image: "https://images.unsplash.com/photo-1584961958654-fea280e63da5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
        featured: true,
        description: "In a COVID-19 world, a major debate exists: do masks make a difference? Let's find out!",
        length: 121,
        release: "06/02/20",
        language: "English",
        rating: 5,
        ratingCount: 963,
    },
    {
        id: 32,
        title: "Ancient Marvels",
        author: "Dr. James Gunner",
        category: "Science",
        image: "https://images.unsplash.com/photo-1503152394-c571994fd383?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80",
        featured: false,
        description: "Did you know that the way mankind built ancient buildings isn't too different from today?",
        length: 199,
        release: "12/06/19",
        language: "English",
        rating: 4,
        ratingCount: 24,
    },
    {
        id: 33,
        title: "Sky Ramparts",
        author: "A.A. Bay",
        category: "SciFi",
        image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=631&q=80",
        featured: false,
        description: "A young girl living in a floating castle falls to Earth, and she must find her way back to the sky.",
        length: 234,
        release: "04/10/20",
        language: "English",
        rating: 5,
        ratingCount: 94,
    },
    {
        id: 34,
        title: "Sleeping Nerdy",
        author: "R. Kline",
        category: "SciFi",
        image: "https://images.unsplash.com/photo-1546443046-ed1ce6ffd1ab?ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80",
        featured: true,
        description: "A die-hard gamer falls into a coma, and the only way to wake her lies inside a videogame.",
        length: 174,
        release: "06/28/19",
        language: "English",
        rating: 4,
        ratingCount: 115,
    },
    {
        id: 35,
        title: "Queen's Eye",
        author: "Madam Dest",
        category: "SciFi",
        image: "https://images.unsplash.com/photo-1541554685626-8016b713c293?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80",
        featured: false,
        description: "Seeing is believing, and only she can see what's coming next for nation, and it isn't looking good.",
        length: 190,
        release: "08/17/18",
        language: "English",
        rating: 3,
        ratingCount: 111,
    },
    {
        id: 36,
        title: "Art of Protest",
        author: "Val Minz",
        category: "Social Science",
        image: "https://images.unsplash.com/photo-1503249023995-51b0f3778ccf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=611&q=80",
        featured: false,
        description: "There is a fine line between protest and anarchy. Walking it well is the key to progress.",
        length: 432,
        release: "06/17/16",
        language: "English",
        rating: 4,
        ratingCount: 1096,
    },
    {
        id: 37,
        title: "Bone Daddy",
        author: "Charles Mans",
        category: "Social Science",
        image: "https://images.unsplash.com/photo-1511309033101-c50362cbb763?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1267&q=80",
        featured: true,
        description: "The story behind the Skull Museum, and the renowned archaeologist who founded it.",
        length: 161,
        release: "07/16/19",
        language: "English",
        rating: 5,
        ratingCount: 194,
    },
    {
        id: 38,
        title: "Colors of the World",
        author: "Dana Tibb",
        category: "Social Science",
        image: "https://images.unsplash.com/photo-1535483102974-fa1e64d0ca86?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1234&q=80",
        featured: false,
        description: "Just where do the the flags of each country come from, and what do they represent?",
        length: 642,
        release: "08/08/18",
        language: "English",
        rating: 4,
        ratingCount: 67,
    },
    {
        id: 39,
        title: "Mind Palace",
        author: "Lou Y Kay",
        category: "Wellness",
        image: "https://images.unsplash.com/uploads/14122810486321888a497/1b0cc699?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1051&q=80",
        featured: true,
        description: "It's time to take control of your memories, and be able to access any of them at any time.",
        length: 147,
        release: "7/31/19",
        language: "English",
        rating: 5,
        ratingCount: 222,
    },
    {
        id: 40,
        title: "Love Out Loud",
        author: "Jackie Bee",
        category: "Wellness",
        image: "https://images.unsplash.com/reserve/Af0sF2OS5S5gatqrKzVP_Silhoutte.jpg?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
        featured: false,
        description: "Expressing feelings is hard. These 7 steps can help you own your feelings fearlessly express them.",
        length: 97,
        release: "10/2/20",
        language: "English",
        rating: 4,
        ratingCount: 3,
    },
    {
        id: 41,
        title: "Feeding Frenzy",
        author: "Booker Lane",
        category: "Wellness",
        image: "https://images.unsplash.com/photo-1535914254981-b5012eebbd15?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
        featured: false,
        description: "You are what you eat! However, how do you feed the rest of you, not just your body?",
        length: 113,
        release: "2/28/18",
        language: "English",
        rating: 4,
        ratingCount: 399,
    },
    {
        id: 42,
        title: "WanderWoman",
        author: "Remi Lou Gates",
        category: "Young Adult",
        image: "https://images.unsplash.com/photo-1482348838597-b97cc6c86a88?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1502&q=80",
        featured: false,
        description: "Misha was bored, so she decided to do something crazy: visit every country by foot!",
        length: 159,
        release: "03/06/19",
        language: "English",
        rating: 4,
        ratingCount: 172,
    },
    {
        id: 43,
        title: "Gin with A Twist",
        author: "L.M. Ohzo",
        category: "Young Adult",
        image: "https://images.unsplash.com/photo-1597824583262-90e3153a21eb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80",
        featured: true,
        description: "Jen is your average bartender at a local haunt by day, and a 'bartender' for the mafia at night.",
        length: 222,
        release: "06/18/17",
        language: "English",
        rating: 5,
        ratingCount: 257,
    },
    {
        id: 44,
        title: "Forever Old",
        author: "Martha Keenie",
        category: "Young Adult",
        image: "https://images.unsplash.com/photo-1533749047139-189de3cf06d3?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=752&q=80",
        featured: false,
        description: "When Jack turned 13, the strangest thing happens: he turned 100 instead!",
        length: 199,
        release: "07/03/02",
        language: "English",
        rating: 3,
        ratingCount: 300,
    },
];