export const FEATUREDBOOKS = [
    {
        id_a: 0,
        title_a: "The Rook",
        author_a: "M.D. Gardner",
        category_a: "Adventure",
        image_a: "https://images.unsplash.com/photo-1550368566-f9cc32d7392d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80",
        featured_a: true,
        description_a: "When all else falls in the war on magic, he alone stands tall, thanks to his wits and rings.",
        length_a: 242,
        release_a: "10/23/19",
        language_a: "English",
        rating_a: 4,
        ratingCount_a: 313,

        id_b: 1,
        title_b: "By The Numbers",
        author_b: "Luke Limon",
        category_b: "Business",
        image_b: "https://images.unsplash.com/photo-1506555191898-a76bacf004ca?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=668&q=80",
        featured_b: true,
        description_b: "An MBA is just a degree. If you want to get a business education, start here!",
        length_b: 161,
        release_b: "04/07/10",
        language_b: "English",
        rating_b: 5,
        ratingCount_b: 1000,

        id_c: 2,
        title_c: "Fiona Found",
        author_c: "Molli Miles",
        category_c: "Mystery",
        image_c: "https://images.unsplash.com/photo-1528728329032-2972f65dfb3f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80",
        featured_c: true,
        description_c: "One day she's falls asleep in her family's field in 1297. She wakes up in Berlin 2020.",
        length_c: 333,
        release_c: "02/14/19",
        language_c: "English",
        rating_c: 5,
        ratingCount_c: 543,
    },
    {
        id_a: 3,
        title_a: "The Dawn",
        author_a: "Kaya Dee Knox",
        category_a: "Romance",
        image_a: "https://images.unsplash.com/photo-1473679408190-0693dd22fe6a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
        featured_a: true,
        description_a: "A once-in-a-lifetime sunrise accidentally brings two old friends back together.",
        length_a: 140,
        release_a: "06/20/18",
        language_a: "English",
        rating_a: 5,
        ratingCount_a: 113,

        id_b: 4,
        title_b: "Mask or No Mask?",
        author_b: "Scott Bonnet",
        category_b: "Science",
        image_b: "https://images.unsplash.com/photo-1584961958654-fea280e63da5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
        featured_b: true,
        description_b: "In a COVID-19 world, a major debate exists: do masks make a difference? Let's find out!",
        length_b: 121,
        release_b: "06/02/20",
        language_b: "English",
        rating_b: 5,
        ratingCount_b: 963,

        id_c: 5,
        title_c: "Sleeping Nerdy",
        author_c: "R. Kline",
        category_c: "SciFi",
        image_c: "https://images.unsplash.com/photo-1546443046-ed1ce6ffd1ab?ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80",
        featured_c: true,
        description_c: "A die-hard gamer falls into a coma, and the only way to wake her lies inside a videogame.",
        length_c: 174,
        release_c: "06/28/19",
        language_c: "English",
        rating_c: 4,
        ratingCount_c: 115,
    },
    {
        id_a: 6,
        title_a: "Bone Daddy",
        author_a: "Charles Mans",
        category_a: "Social Science",
        image_a: "https://images.unsplash.com/photo-1511309033101-c50362cbb763?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1267&q=80",
        featured_a: true,
        description_a: "The story behind the Skull Museum, and the renowned archaeologist who founded it.",
        length_a: 161,
        release_a: "07/16/19",
        language_a: "English",
        rating_a: 5,
        ratingCount_a: 194,

        id_b: 7,
        title_b: "Mind Palace",
        author_b: "Lou Y Kay",
        category_b: "Wellness",
        image_b: "https://images.unsplash.com/uploads/14122810486321888a497/1b0cc699?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1051&q=80",
        featured_b: true,
        description_b: "It's time to take control of your memories, and be able to access any of them at any time.",
        length_b: 147,
        release_b: "7/31/19",
        language_b: "English",
        rating_b: 5,
        ratingCount_b: 222,

        id_c: 8,
        title_c: "Gin with A Twist",
        author_c: "L.M. Ohzo",
        category_c: "Young Adult",
        image_c: "https://images.unsplash.com/photo-1597824583262-90e3153a21eb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80",
        featured_c: true,
        description_c: "Jen is your average bartender at a local haunt by day, and a 'bartender' for the mafia at night.",
        length_c: 222,
        release_c: "06/18/17",
        language_c: "English",
        rating_c: 5,
        ratingCount_c: 257,
    },
];